version: "3"
services: 
    app:
        image: crud
        depends_on: 
            - db
        links: 
            - "db"
        ports: 
            - "8000:8000"
        networks: 
            - monreseau

    db:
        image: postgres
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_PASSWORD: root
        networks: 
            - monreseau
        volumes: 
            - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

networks: 
    monreseau:
